const TRACE_SUPABASE_URL='https://qzsgjyrtlitawsgepwwc.supabase.co';
const TRACE_SUPABASE_KEY='sb_publishable_Ca8qpAae0tHAnecrXmlozQ_X5BsZeI1';
(function(){
 const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;s.onerror=()=>console.error('Trace: Supabase client failed to load');document.head.appendChild(s);
 let sb,oldSet,hydrating=false;const localKey='ia2';
 function msg(t){const el=document.getElementById('tsMsg');if(el)el.textContent=t}
 function addUI(){if(document.getElementById('traceUser'))return;const b=document.createElement('button');b.id='traceUser';b.className='btn trace-user';b.setAttribute('aria-label','Account status');b.innerHTML='<span class="trace-user-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.2"></circle><path d="M5.5 19c.8-3.2 3-5 6.5-5s5.7 1.8 6.5 5"></path></svg></span><span class="trace-user-dot"></span>';b.title='Checking account…';const style=document.createElement('style');style.textContent='.trace-user{position:relative;width:40px;height:40px;padding:0;display:grid;place-items:center;border-radius:50%;margin-left:4px}.trace-user-icon{display:grid;place-items:center;color:#8e97a8}.trace-user-dot{position:absolute;right:5px;bottom:5px;width:8px;height:8px;border-radius:50%;background:#4b5361;border:2px solid #10131a}.trace-user.signed-in{border-color:#b7ff6a;background:#141b12}.trace-user.signed-in .trace-user-icon{color:#b7ff6a}.trace-user.signed-in .trace-user-dot{background:#b7ff6a;box-shadow:0 0 8px #b7ff6a88}.trace-user.signed-out .trace-user-dot{background:#657083}@media(max-width:560px){.trace-user{width:36px;height:36px}.trace-user-dot{right:4px;bottom:4px}}';document.head.appendChild(style);const tabs=document.querySelector('.tabs');if(tabs)tabs.appendChild(b);b.onclick=()=>openAuth();updateUserUI()}
 async function updateUserUI(user){const b=document.getElementById('traceUser');if(!b)return;user=user===undefined?await getUser():user;if(user){b.classList.add('signed-in');b.classList.remove('signed-out');b.title='Logged in · '+(user.email||'Account')}else{b.classList.add('signed-out');b.classList.remove('signed-in');b.title='Not logged in · Click to sign in'} }
 function openAuth(){let m=document.getElementById('traceSyncModal');if(!m){m=document.createElement('div');m.id='traceSyncModal';m.className='modal';m.innerHTML='<div class="modalbox"><div class="top"><div><div class="ey">Cross-device memory</div><h2 style="margin:4px 0">Sync Trace</h2></div><button class="btn" id="tsClose">×</button></div><p class="small" style="line-height:1.6">Use the same account on your phone and desktop. Your activities, journal and statistics can then follow you everywhere.</p><form class="form" id="tsForm"><input id="tsEmail" type="email" required autocomplete="email" placeholder="Email"><input id="tsPass" type="password" required minlength="6" autocomplete="current-password" placeholder="Password"><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary">Sign in</button><button class="btn" type="button" id="tsCreate">Create account</button><button class="btn" type="button" id="tsSignOut">Sign out</button></div><div class="small" id="tsMsg"></div></form></div>';document.body.appendChild(m);m.querySelector('#tsClose').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.querySelector('#tsForm').onsubmit=async e=>{e.preventDefault();msg('Signing in…');const email=document.getElementById('tsEmail').value.trim(),password=document.getElementById('tsPass').value;const r=await sb.auth.signInWithPassword({email,password});if(r.error){msg(r.error.message);return}msg('Signed in. Syncing…');await syncNow();updateUserUI(r.data?.user);m.classList.remove('open')};m.querySelector('#tsCreate').onclick=async()=>{const email=document.getElementById('tsEmail').value.trim(),password=document.getElementById('tsPass').value;if(!email||password.length<6){msg('Enter an email and a password of at least 6 characters.');return}msg('Creating account…');const r=await sb.auth.signUp({email,password});if(r.error){msg(r.error.message);return}if(r.data?.session){msg('Account created. Syncing now…');await syncNow();updateUserUI(r.data.user);setTimeout(()=>m.classList.remove('open'),400)}else msg('Account created. If email confirmation is still enabled, check your inbox before signing in.')};m.querySelector('#tsSignOut').onclick=async()=>{await sb.auth.signOut();updateUserUI(null);msg('Signed out. Local data remains on this device.')}}m.classList.add('open');updateUserUI()}
 async function getUser(){const r=await sb.auth.getUser();return r.data?.user||null}
 async function pull(){const user=await getUser();if(!user)return false;const r=await sb.from('app_state').select('payload,updated_at').eq('user_id',user.id).maybeSingle();if(r.error){console.error('Trace pull error',r.error);return false}if(r.data?.payload){hydrating=true;oldSet(localKey,JSON.stringify(r.data.payload));hydrating=false;return true}return false}
 async function push(raw){if(hydrating)return;try{const user=await getUser();if(!user)return;const payload=JSON.parse(raw);const r=await sb.from('app_state').upsert({user_id:user.id,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error)console.error('Trace push error',r.error)}catch(e){console.error('Trace push exception',e)}}
 async function syncNow(){const user=await getUser();if(!user){openAuth();return}const raw=localStorage.getItem(localKey);if(raw)await push(raw);await pull()}
 async function boot(){sb=window.supabase.createClient(TRACE_SUPABASE_URL,TRACE_SUPABASE_KEY);addUI();oldSet=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){oldSet(k,v);if(k===localKey&&!hydrating)push(v)};const session=(await sb.auth.getSession()).data.session;updateUserUI(session?.user||null);if(session)await pull();sb.auth.onAuthStateChange(async(event,session)=>{updateUserUI(session?.user||null);if(session&&event!=='INITIAL_SESSION')await syncNow()})}
 window.addEventListener('load',()=>{const wait=()=>window.supabase?boot():setTimeout(wait,50);wait()});
})();
