const TRACE_SUPABASE_URL='https://qzsgjyrtlitawsgepwwc.supabase.co';
const TRACE_SUPABASE_KEY='sb_publishable_Ca8qpAae0tHAnecrXmlozQ_X5BsZeI1';
(function(){
 const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;s.onerror=()=>{};document.head.appendChild(s);
 let sb,oldSet;
 function addUI(){if(document.getElementById('traceSync'))return;const b=document.createElement('button');b.id='traceSync';b.className='btn';b.textContent='☁ Sync';b.title='Sync Trace across devices';const tabs=document.querySelector('.tabs');if(tabs)tabs.appendChild(b);b.onclick=()=>openAuth();}
 function openAuth(){let m=document.getElementById('traceSyncModal');if(!m){m=document.createElement('div');m.id='traceSyncModal';m.className='modal';m.innerHTML='<div class="modalbox"><div class="top"><div><div class="ey">Cross-device memory</div><h2 style="margin:4px 0">Sync Trace</h2></div><button class="btn" id="tsClose">×</button></div><p class="small" style="line-height:1.6">Use the same account on your phone and desktop. Your activities and journal will then stay in one database.</p><form class="form" id="tsForm"><input id="tsEmail" type="email" required placeholder="Email"><input id="tsPass" type="password" required minlength="6" placeholder="Password"><div style="display:flex;gap:8px"><button class="btn primary">Sign in</button><button class="btn" type="button" id="tsCreate">Create account</button></div><div class="small" id="tsMsg"></div></form></div>';document.body.appendChild(m);m.querySelector('#tsClose').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.querySelector('#tsForm').onsubmit=async e=>{e.preventDefault();const email=tsEmail.value, password=tsPass.value;const r=await sb.auth.signInWithPassword({email,password});if(r.error){tsMsg.textContent=r.error.message;return}await pull();m.classList.remove('open');location.reload()};m.querySelector('#tsCreate').onclick=async()=>{const r=await sb.auth.signUp({email:tsEmail.value,password:tsPass.value});tsMsg.textContent=r.error?r.error.message:'Account created. Sign in after confirmation if required.';};}m.classList.add('open');}
 async function pull(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const r=await sb.from('app_state').select('payload').eq('user_id',user.id).maybeSingle();if(!r.error&&r.data?.payload)localStorage.setItem('ia2',JSON.stringify(r.data.payload));}
 async function push(raw){try{const {data:{user}}=await sb.auth.getUser();if(!user)return;const payload=JSON.parse(raw);await sb.from('app_state').upsert({user_id:user.id,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'});}catch(e){} }
 async function boot(){sb=window.supabase.createClient(TRACE_SUPABASE_URL,TRACE_SUPABASE_KEY);addUI();oldSet=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){oldSet(k,v);if(k==='ia2')push(v)};const {data:{session}}=await sb.auth.getSession();if(session)await pull();}
 window.addEventListener('load',()=>{const wait=()=>window.supabase?boot():setTimeout(wait,50);wait();});
})();
