const TRACE_SUPABASE_URL='https://qzsgjyrtlitawsgepwwc.supabase.co';
const TRACE_SUPABASE_KEY='sb_publishable_Ca8qpAae0tHAnecrXmlozQ_X5BsZeI1';
const TRACE_OWNER_USER_ID='69426c35-da44-467f-971f-4c4c26cd75da';
(function(){
 const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;s.onerror=()=>console.error('Trace: Supabase client failed to load');document.head.appendChild(s);
 let sb,oldSet,hydrating=false,channel;const localKey='ia2';
 function msg(t){const el=document.getElementById('tsMsg');if(el)el.textContent=t}
 function addUI(){if(document.getElementById('traceUser'))return;const b=document.createElement('button');b.id='traceUser';b.className='btn trace-user';b.setAttribute('aria-label','Account status');b.innerHTML='<span class="trace-user-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="3.2"></circle><path d="M5.5 19c.8-3.2 3-5 6.5-5s5.7 1.8 6.5 5"></path></svg></span><span class="trace-user-dot"></span>';b.title='Checking account…';const style=document.createElement('style');style.textContent='.trace-user{position:relative;width:40px;height:40px;padding:0;display:grid;place-items:center;border-radius:50%;margin-left:4px}.trace-user-icon{display:grid;place-items:center;color:#8e97a8}.trace-user-dot{position:absolute;right:5px;bottom:5px;width:8px;height:8px;border-radius:50%;background:#4b5361;border:2px solid #10131a}.trace-user.signed-in{border-color:#b7ff6a;background:#141b12}.trace-user.signed-in .trace-user-icon{color:#b7ff6a}.trace-user.signed-in .trace-user-dot{background:#b7ff6a;box-shadow:0 0 8px #b7ff6a88}.trace-user.signed-out .trace-user-dot{background:#657083}@media(max-width:560px){.trace-user{width:36px;height:36px}.trace-user-dot{right:4px;bottom:4px}}';document.head.appendChild(style);const tabs=document.querySelector('.tabs');if(tabs)tabs.appendChild(b);b.onclick=()=>openAuth();updateUserUI()}
 async function updateUserUI(user){const b=document.getElementById('traceUser');if(!b)return;user=user===undefined?await getUser():user;if(user&&user.id===TRACE_OWNER_USER_ID){b.classList.add('signed-in');b.classList.remove('signed-out');b.title='Logged in · Trace owner'}else{b.classList.add('signed-out');b.classList.remove('signed-in');b.title='Not logged in · Click to sign in'}}
 function openAuth(){let m=document.getElementById('traceSyncModal');if(!m){m=document.createElement('div');m.id='traceSyncModal';m.className='modal';m.innerHTML='<div class="modalbox"><div class="top"><div><div class="ey">Your private Trace</div><h2 style="margin:4px 0">Account</h2></div><button class="btn" id="tsClose">×</button></div><p class="small" style="line-height:1.6">Trace is currently private to its owner. Sign in on every device with the same account and your activities, journal and statistics will follow you.</p><form class="form" id="tsForm"><input id="tsEmail" type="email" required autocomplete="email" placeholder="Email"><input id="tsPass" type="password" required minlength="6" autocomplete="current-password" placeholder="Password"><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary">Sign in</button><button class="btn" type="button" id="tsSignOut">Sign out</button></div><div class="small" id="tsMsg"></div></form></div>';document.body.appendChild(m);m.querySelector('#tsClose').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};m.querySelector('#tsForm').onsubmit=async e=>{e.preventDefault();msg('Signing in…');const email=document.getElementById('tsEmail').value.trim(),password=document.getElementById('tsPass').value;const r=await sb.auth.signInWithPassword({email,password});if(r.error){msg(r.error.message);return}if(r.data?.user?.id!==TRACE_OWNER_USER_ID){await sb.auth.signOut();msg('This Trace is private to its owner.');updateUserUI(null);return}msg('Signed in. Syncing…');await syncNow();updateUserUI(r.data.user);m.classList.remove('open')};m.querySelector('#tsSignOut').onclick=async()=>{await sb.auth.signOut();updateUserUI(null);msg('Signed out. Your cloud data remains safe.')}}m.classList.add('open');updateUserUI()}
 async function getUser(){const r=await sb.auth.getUser();return r.data?.user||null}
 async function pull(){const user=await getUser();if(!user||user.id!==TRACE_OWNER_USER_ID)return false;const r=await sb.from('app_state').select('payload,updated_at').eq('user_id',user.id).maybeSingle();if(r.error){console.error('Trace pull error',r.error);msg('Sync read failed. Check your connection.');return false}if(r.data?.payload){hydrating=true;oldSet(localKey,JSON.stringify(r.data.payload));hydrating=false;if(typeof window.render==='function')window.render();window.dispatchEvent(new CustomEvent('trace:remote-sync'));return true}return false}
 async function push(raw){if(hydrating)return;try{const user=await getUser();if(!user||user.id!==TRACE_OWNER_USER_ID)return;const payload=JSON.parse(raw);const r=await sb.from('app_state').upsert({user_id:user.id,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(r.error){console.error('Trace push error',r.error);msg('Cloud sync failed.')}}catch(e){console.error('Trace push exception',e);msg('Cloud sync failed.')}}
 async function syncNow(){const user=await getUser();if(!user||user.id!==TRACE_OWNER_USER_ID){openAuth();return}await pull();const raw=localStorage.getItem(localKey);if(raw)await push(raw)}
 function subscribeRealtime(){if(channel)sb.removeChannel(channel);channel=sb.channel('trace-owner-state').on('postgres_changes',{event:'*',schema:'public',table:'app_state',filter:'user_id=eq.'+TRACE_OWNER_USER_ID},payload=>{if(payload.eventType==='DELETE')return;const remote=payload.new?.payload;if(remote){hydrating=true;oldSet(localKey,JSON.stringify(remote));hydrating=false;if(typeof window.render==='function')window.render();window.dispatchEvent(new CustomEvent('trace:remote-sync'));}}).subscribe(status=>{if(status==='SUBSCRIBED')console.log('Trace: live sync connected');});}
 async function boot(){sb=window.supabase.createClient(TRACE_SUPABASE_URL,TRACE_SUPABASE_KEY);addUI();oldSet=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){oldSet(k,v);if(k===localKey&&!hydrating)push(v)};const session=(await sb.auth.getSession()).data.session;if(session?.user?.id===TRACE_OWNER_USER_ID){updateUserUI(session.user);await pull();subscribeRealtime()}else if(session){await sb.auth.signOut();updateUserUI(null)}else updateUserUI(null);sb.auth.onAuthStateChange(async(event,session)=>{if(session?.user?.id===TRACE_OWNER_USER_ID){updateUserUI(session.user);if(event!=='INITIAL_SESSION'){await syncNow();subscribeRealtime()}}else{if(session)await sb.auth.signOut();updateUserUI(null)}})}
 window.addEventListener('load',()=>{const wait=()=>window.supabase?boot():setTimeout(wait,50);wait()});
})();
